Repository neicnordic/sda-doa, pull requests merged in 2020-05, with the labels that each got.

#18 Env-vars description and JavaDocs
  README.md
  src/main/java/no/uio/ifi/localega/doa/LocalEGADOAApplication.java
  src/main/java/no/uio/ifi/localega/doa/aspects/AAIAspect.java
  src/main/java/no/uio/ifi/localega/doa/dto/DestinationFormat.java
  src/main/java/no/uio/ifi/localega/doa/dto/File.java
  src/main/java/no/uio/ifi/localega/doa/model/LEGADataset.java
  src/main/java/no/uio/ifi/localega/doa/model/LEGAFile.java
  src/main/java/no/uio/ifi/localega/doa/repositories/DatasetRepository.java
  src/main/java/no/uio/ifi/localega/doa/repositories/FileRepository.java
  src/main/java/no/uio/ifi/localega/doa/rest/MetadataController.java
  src/main/java/no/uio/ifi/localega/doa/rest/StreamingController.java
Labels: documentation

#19 Fix POSIX backend (archive path computation)
  src/main/java/no/uio/ifi/localega/doa/rest/StreamingController.java
Labels: bug

#20 Fix null values in view for file_database
  src/main/java/no/uio/ifi/localega/doa/aspects/AAIAspect.java
  src/main/java/no/uio/ifi/localega/doa/rest/MetadataController.java
Labels: bug

#21 Make SSL mode be configurable in JDBC
  README.md
  src/main/resources/application.yml
Labels: enhancement
